### ISSUE TITLE
How can I create a bool constant?

### ISSUE THREAD

**Issue by Flians** [usi-verification-and-security/opensmt#113]
I used new " THandler(*uftheory)->getLogic().mkConst(val); "

It shows "There is no instance of overloaded function "Logic :: mkConst" that matches the parameter list-the parameter type is: (const int)-the object type is: Logic"

**Comment by blishko** [comment]
Hi @Flians ,

please always include all the relevant code, from your line it is not clear what "val" is.

In any case, have a look at the test1.cc in the examples folder. There you can see how to create a new boolean variable: `logic.mkBoolVar("a")` where "a" is the name of the variable.
If you want to access boolean constants TRUE and FALSE use the following:
```
logic.getTerm_true();
logic.getTerm_false();
```

**Comment by Flians** [comment]
Hi,
Thank you. I got it. And my problem has been solved.

Best regards

Rongliang Fu
发件人: Martin Blicha<mailto:notifications@github.com>
发送时间: 2020年5月28日 14:37
收件人: usi-verification-and-security/opensmt<mailto:opensmt@noreply.github.com>
抄送: Rongliang Fu<mailto:rongliangfu@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [usi-verification-and-security/opensmt] How can I create a bool constant? (#113)


Hi @Flians<https://github.com/Flians> ,

please always include all the relevant code, from your line it is not clear what "val" is.

In any case, have a look at the test1.cc in the examples folder. There you can see how to create a new boolean variable: logic.mkBoolVar("a") where "a" is the name of the variable.
If you want to access boolean constants TRUE and FALSE use the following:

logic.getTerm_true();

logic.getTerm_false();

―

**Comment by blishko** [comment]
Great!
