### ISSUE TITLE
For test-bv.cc, Why the result of this "2 + 1 2" is 1 ?

### ISSUE THREAD

**Issue by Flians** [usi-verification-and-security/opensmt#122]
For test-bv.cc, Why the result of this "2 + 1 2" is 1 ?

```
L-T95HG8WN-1422:build flynn$ ./test-bv 2 "+" 1 2
Computing 1 (01) + 2 (10)
sat
1 (01)
L-T95HG8WN-1422:build flynn$ ./test-bv 2 '/' 00 00
Computing 00 (00) / 00 (00)
sat
3 (11)
L-T95HG8WN-1422:build flynn$ ./test-bv 2 '/' 00 01
Computing 00 (00) / 01 (01)
sat
3 (11)
L-T95HG8WN-1422:build flynn$ ./test-bv 2 '/' 01 01
Computing 01 (01) / 01 (01)
sat
3 (11)
```

**Comment by Flians** [comment]
How can I resolve this problem? The file test-bv.cc is from [your examples](https://github.com/usi-verification-and-security/opensmt/blob/master/examples/test-bv.cc).

**Comment by aehyvari** [comment]
Hi Rongliang,

These are currently not our priority in the development.  They are related
to the bit vector implementation in the code that is not officially
supported.  You can safely ignore these files.

Best Regards,
Antti

**Comment by Flians** [comment]
Hi @aehyvari ,
Now I wanna verify three-valued logic. 
So I wanna use 2 bit to present TRUE, FALSE, and UNKNOWN.
How can I do this use opensmt?
![image](https://user-images.githubusercontent.com/16850481/84219430-198acd80-ab03-11ea-8933-d492b40fb73a.png)

**Comment by andrewvaughanj** [comment]
For context: https://github.com/Z3Prover/z3/issues/4497

**Comment by Flians** [comment]
@andrewvaughanj 
Feel that you are involved in the development of all smt projects.
Awesome!
Thank you!
