### ISSUE TITLE
Build option for static library only

### ISSUE THREAD

**Issue by leonardoalt** [usi-verification-and-security/opensmt#132]
It would be nice to have a build option that only generates `libopensmt2.a`, without the shared library and the executable.
This is useful for systems that use the solver via the API.

**Comment by blishko** [comment]
I agree that this should be possible. It is on my long TODO list and it has just moved closer to the top :)

**Comment by andrewvaughanj** [comment]
@leonardoalt could you take a look at https://github.com/usi-verification-and-security/opensmt/pull/133 ?

**Comment by blishko** [comment]
@leonardoalt Do you also want to be able to install the static library (e.g., with `make install`)?
I think the current set-up is that only the executable and the shared library are installed this way.

**Comment by leonardoalt** [comment]
@blishko I'm fine without it being part of `make install`

**Comment by blishko** [comment]
I think we can close this one. 
Thanks @andrewvaughanj !

The next step will be dealt with in a separate issue (#135)
