### ISSUE TITLE
memory leak at smt2newparse

### ISSUE THREAD

**Issue by rainoftime** [usi-verification-and-security/opensmt#157]
Hi, for this formula
[leak.txt](https://github.com/usi-verification-and-security/opensmt/files/5005480/leak.txt)

opensmt c857e2746ea20e901e201d9d909e2c119a63a625
~~~~
At line 174781: memory exhausted

=================================================================
==48084==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 4194264 byte(s) in 174761 object(s) allocated from:
    #0 0x7f114047d592 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99592)
    #1 0x5e06a3 in smt2newparse(Smt2newContext*) /home/peisen/test/tofuzz/opensmt/build/src/parsers/smt2new/smt2newparser.yy:406
    #2 0x565b24 in Interpret::interpFile(_IO_FILE*) /home/peisen/test/tofuzz/opensmt/src/api/Interpret.cc:1115
    #3 0x556666 in main /home/peisen/test/tofuzz/opensmt/src/bin/opensmt.cc:148
    #4 0x7f113ee4d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

Direct leak of 4194264 byte(s) in 174761 object(s) allocated from:
    #0 0x7f114047d592 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x99592)
    #1 0x5e0607 in smt2newparse(Smt2newContext*) /home/peisen/test/tofuzz/opensmt/build/src/parsers/smt2new/smt2newparser.yy:400
    #2 0x565b24 in Interpret::interpFile(_IO_FILE*) /home/peisen/test/tofuzz/opensmt/src/api/Interpret.cc:1115
    #3 0x556666 in main /home/peisen/test/tofuzz/opensmt/src/bin/opensmt.cc:148
    #4 0x7f113ee4d82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
~~~~

**Comment by blishko** [comment]
Hi @rainoftime ,
Thanks for this example.
According to our analysis, this is not a memory leak, but with the huge number of nested lets this example has reached a limit  in the first phase of our parser. The program then ends abruptly and the memory is not properly released, but the program has stopped abnormally so it is not really a memory leak.

We could increase the limit in the parser, but so far we have not seen the need for this in the usual problems we work with.
Is there a practical application where such examples arise?

**Comment by rainoftime** [comment]
I have not encountered the issue in real-world cases

**Comment by rainoftime** [comment]
Another instance at 25e997239898 
[leak.txt](https://github.com/usi-verification-and-security/opensmt/files/5156113/leak.txt)
