### ISSUE TITLE
Potential performance issue on QF_LRA formula

### ISSUE THREAD

**Issue by rainoftime** [usi-verification-and-security/opensmt#158]
Hi, for the following formula
[slow.txt](https://github.com/usi-verification-and-security/opensmt/files/5014402/slow.txt)

opensmtc 857e2746ea
~~~~~
time z3 f.smt2
sat

real    0m1.924s
user    0m1.836s
sys     0m0.084s


time opensmt f.smt2
sat

real    1m15.247s
user    1m15.104s
sys     0m0.144s

**Comment by blishko** [comment]
Hi @rainoftime !
We have already noticed this problem thanks to your previous example #157 and we have a fix ready.
Thanks!

**Comment by rainoftime** [comment]
Do you mean this is also caused by the parser (not the engine)?

**Comment by blishko** [comment]
It's related to the last phase in our parsing process. The problem is not in the Bison parser we use, but in how we process the parsed AST.
