### ISSUE TITLE
How to setup query_timer?

### ISSUE THREAD

**Issue by Flians** [usi-verification-and-security/opensmt#169]
I find the param "query_timer" in  MainSolver.cc. 
Can I change it, and how can I setup it?

![image](https://user-images.githubusercontent.com/16850481/93551803-5c313100-f9a1-11ea-8bc5-5dac11eea250.png)

**Comment by aehyvari** [comment]
Hi Flians,

You should be able to enable it by having (set-option :time-queries) in the smtlib2 file.

However I feel I should point out that this is code that we use for some internal benchmarking.  I suppose there's ambiguity in what constitutes a query, but if you interpret a query the same way we do, then I guess you're good to go.

- Antti

**Comment by Flians** [comment]
Hi Antti,
Yes, I know that I cant use ` config->setOption(SMTConfig::o_time_queries, SMTOption(true), msg);` to set `time-queries`.
But it is used to record how much time we spend solving.
What should I do if I want to set a query time limit?

Best,
Flians

**Comment by aehyvari** [comment]
Ah ok, yes, the system is designed to just measure the time a query takes.

We don't support limiting the query time at the moment, but it could be a good future feature.  It could maybe be implemented as an API call for stopping the solver, that the user could call from a separate thread.  I'm open to ideas.

**Comment by Flians** [comment]
I got it. 
Thank you.
