### ISSUE TITLE
Quoting of variable names in printing

### ISSUE THREAD

**Issue by aehyvari** [usi-verification-and-security/opensmt#173]
For instance through the API a user may declare a variable with a name that would be illegal in smtlib2, e.g., an integer literal such as 7.  Opensmt supports dumping these declared problems into the smtlib2 format, but does not quote the illegal variable names into legal ones, resulting in incorrect smtlib2.

**Comment by blishko** [comment]
@aehyvari, was this fixed in #422 or is there more work that needs to be done?
