### ISSUE TITLE
Duplicate literals in explanation of a conflict in Egraph solver

### ISSUE THREAD

**Issue by blishko** [usi-verification-and-security/opensmt#19]
An explanation of a conflict in Egraph contains duplicate literals.
The problem was introduced in b30133f5.
In method Egraph::assertLit, TWO consecutive calls to assertEq are now possible, but if the first one leads to conflict, the second one should not happen (otherwise, it can introduce additional literals to the explanation, which is undesirable).

**Comment by aehyvari** [comment]
Ok, I guess that needs to be fixed.

**Comment by blishko** [comment]
I think I have a fix. I will create a pull request soon.

**Comment by aehyvari** [comment]
Thank you!
