### ISSUE TITLE
Solution soundness issue on QF_UFLRA formula

### ISSUE THREAD

**Issue by rainoftime** [usi-verification-and-security/opensmt#191]
Hi, for the following formula,
opensmt 6617993 yields `sat`,
but both z3 and cvc4 return `unsat`.
~~~~
(set-logic QF_UFLRA)
(declare-fun uf3 (Bool Bool Bool) Bool)
(declare-fun v0 () Bool)
(assert (uf3 v0 (uf3 v0 v0 v0) v0))
(assert (not (uf3 v0 v0 v0)))
(assert (distinct v0 true))
(check-sat)
~~~~

After changing QF_UFLRA to QF_UF, opensmt can solve correctly

**Comment by rainoftime** [comment]
Seems opensmt does not support QF_UFLRA anymore?

**Comment by aehyvari** [comment]
Yes, at the moment there's no support for that combination.  Thanks.
