### ISSUE TITLE
QF_LIA fails to recognize the `div` symbol

### ISSUE THREAD

**Issue by rainoftime** [usi-verification-and-security/opensmt#200]
Hi, for the  following formula
~~~~
(set-logic QF_LIA)
(declare-fun x () Int)
(assert (= (div x 2) 2))
(check-sat)
~~~~
opensmt throws a warning
~~~~
./opensmt f.smt2 
(error "No such symbol div: Unknown symbol `div'")

(error "assertion returns an unknown sort")

sat
~~~~
After changing `div` to `/`, opensmt can solve correctly.
However, according to http://smtlib.cs.uiowa.edu/theories-Ints.shtml,
integer division should use the symbol `div`

**Comment by aehyvari** [comment]
Hi @rainoftime thanks for the issue.  However according to http://smtlib.cs.uiowa.edu/logics-all.shtml#QF_LIA QF_LIA must not have occurrences of `div`.  The theory of integers does have them, as you point out, but they are explicitly excluded in the logic QF_LIA.

**Comment by rainoftime** [comment]
@aehyvari Thanks for the explanation!
Personally, I am a bit confused. Intuitively, one may consider `x div 2` as "linear" (while ` 2 div x` is not).
Besides, opensmt accepts the symbol ` /`. Does it regard as a real division or integer division?
