### ISSUE TITLE
pipe mode is broken

### ISSUE THREAD

**Issue by jwaldmann** [usi-verification-and-security/opensmt#233]
Pipe mode (reading from stdin) is useful (e.g., https://github.com/hgoes/smtlib2/tree/master/backends/pipe , I want it for https://gitlab.imn.htwk-leipzig.de/waldmann/pure-matchbox/-/blob/master/src/LP/SMT.hs )

current implementation seems broken, as I am getting all sorts of scanner/parser errors, e.g.,
```
echo "(set-logic QF_LRA)(declare-fun X () Real)(assert (< 1 X)) (check-sat) (get-value (X))" | ./build/opensmt -p
sat
At interactive input: syntax error, unexpected end of file, expecting ')'
(error "scanner")
```
I do have a fix, and I can submit a PR.

**Comment by jwaldmann** [comment]
Declarations  of variables `par` and `i` must be hoisted outside the inner loop.

**Comment by jwaldmann** [comment]
NB: the scanner tries to count the nesting level of s-expressions by counting characters `(` and `)`, this will break as soon as parens appear in comments, or in string literals.

**Comment by aehyvari** [comment]
Thanks @jwaldmann , this looks very good!  I'll try to have a closer look by tonight.

**Comment by aehyvari** [comment]
Hi @jwaldmann, apologies, it took a while.  Let us know if there are more issues!
