### ISSUE TITLE
Examples are not compiling

### ISSUE THREAD

**Issue by refactormyself** [usi-verification-and-security/opensmt#24]
Hello @aehyvari @blishko following up from my email. I am still have the issue.

I compiled successfully and installed with `sudo make install`. I am working on Ubuntu.
However [examples](https://github.com/usi-verification-and-security/opensmt/tree/master/examples) are not compiling.
Probably not all of the examples, but I run the [make file ](https://github.com/usi-verification-and-security/opensmt/blob/master/examples/Makefile) which is compiling [test_itp.cc](https://github.com/usi-verification-and-security/opensmt/blob/master/examples/test_itp.cc). I also tried to directly compile [test.cc](https://github.com/usi-verification-and-security/opensmt/blob/master/examples/test.cc)

Here is my error:
![image](https://user-images.githubusercontent.com/17991837/59416162-262bf700-8dc5-11e9-9ed3-188f1c0abce9.png)

Also tried [test_c.c](https://github.com/usi-verification-and-security/opensmt/blob/master/examples/test_c.c)

and got this : 
![image](https://user-images.githubusercontent.com/17991837/59416534-d26ddd80-8dc5-11e9-938e-fa294492d038.png)

Thank you

**Comment by aehyvari** [comment]
Hi @refactormyself , we finally got to fix this issue.  I'm not sure if this comes too late for you, but anyway thanks for reporting it!  There's a short README in https://github.com/usi-verification-and-security/opensmt/blob/master/examples/README.md explaining how the examples can be compiled in the build system.

**Comment by refactormyself** [comment]
Thank you. I just build it and the examples are working.
Though it's quite late for the project I had then but I am still interested in SMT Solvers.
