### ISSUE TITLE
Behaviour change in Substitutor class

### ISSUE THREAD

**Issue by blishko** [usi-verification-and-security/opensmt#271]
Either there was a bug in `Substitutor` before or and the change in #260 fixed it, or it was correct before and not ti is buggy, I am not sure which one is true.
In any case, it's behaviour has changed for certain special cases and now it can break the invariant of `Map` that the same key should not be inserted twice.

Given a formula `and a b` and a substitution map `a -> true`, `b -> a` it now behaves differently than before.

**Comment by aehyvari** [comment]
the `mtl::Map` implementation does not work as expected in case the same key is inserted twice (with different data).  This causes in some cases problems.  If a substitution is recorded first in https://github.com/usi-verification-and-security/opensmt/blob/c0e3bd029fc61b61659cec7b75fd306faa03eff5/src/rewriters/Rewriter.h#L61 and then in https://github.com/usi-verification-and-security/opensmt/blob/c0e3bd029fc61b61659cec7b75fd306faa03eff5/src/rewriters/Rewriter.h#L66 only the first substitution will be visible (at least in some cases?).

**Comment by aehyvari** [comment]
I don't want to change the behaviour of mtl::Map.  We could change the Rewriter code instead?  A simple fix, by adding
```C++
substitutions.remove(currentRef);
```
above https://github.com/usi-verification-and-security/opensmt/blob/c0e3bd029fc61b61659cec7b75fd306faa03eff5/src/rewriters/Rewriter.h#L66
fixes the problem and goes through in our ci.  There could be a more elegant fix, but I'm not sure about that.

**Comment by blishko** [comment]
Yes, the second insertion is lost, I believe. Or rather, it will be inserted into the map, but lookup will always find the first inserted value.

I don't think adding `remove` is the proper solution, because it has the precondition that the key is already in the map, but that might not be the case when line 66 is reached.
I would suggest to test if the key is present and if yes then overwrite it, otherwise insert it.

My question for the discussion would be this: Should the rewriter try to rewrite a term that has been changed because its children have been rewritten? I am not sure if we require this behaviour somewhere or not, but it made me think that this does not behave as a simultaneous substitution, which is desired in some cases.
For example, the behaviour in the example I gave at the beginning.
Given a substitution `a -> true`, `b->a` and a formula `and a b` there are two possible behaviours.
Applying simultaneous substitution yield `a`, while applying the substitutions gradually (on the parent after children have been rewritten) yields `true`.
And it can be more complicated, what if we want to substitute complex terms, not only variables? What if we want to rewrite `and a b` to `c`? What should be the result then?

**Comment by blishko** [comment]
The main issue with double insert has been fixed as part of #275.

Regarding the different behaviours of the substitutions, the consensus is that the general `Rewriter` class will probably need to be extended and we will have different `Substitutors` for different desired behaviours.

I am closing this for now.
