### ISSUE TITLE
Assertion faliure during opensmt interpolant construction

### ISSUE THREAD

**Issue by BritikovKI** [usi-verification-and-security/opensmt#459]
## Status Quo

During the interpolant construction using this [file](https://drive.google.com/file/d/1W1rpwkTvzph85cW63A3qMwo1Vy199Bjp/view?usp=sharing) the assertion fails. Here is the received message:
`Assertion failed: (from->next == nullptr), function addCEdge, file /Users/konstantin.britikov/Documents/opensmt/src/tsolvers/egraph/UFInterpolator.cc, line 101.`

## Acceptance criteria

Interpolation search doesn't fail.

**Comment by blishko** [comment]
Here is minimal example that triggers the same assertion:
```
(set-option :produce-interpolants 1)
(set-logic QF_UF)
(declare-sort U 0)
(declare-fun p () Bool)
(declare-fun q () Bool)
(declare-fun r () Bool)
(declare-fun s () U)
(declare-fun u () U)
(declare-fun v () U)
(declare-fun x () U)
(declare-fun C (Bool U) U)
(assert (! (and (= x (C p u)) p) :named A1))
(assert (! (and q r) :named B1))
(assert (! (and (= u s)) :named A2))
(assert (! (and (= s (C q u)) (= v (C r u)) (not (= u v))) :named B2))
(check-sat)
(get-interpolants (and A1 A2) (and B1 B2))
```
