### ISSUE TITLE
Move parallel splitter classes to smts

### ISSUE THREAD

**Issue by aehyvari** [usi-verification-and-security/opensmt#475]
I don't know how to comment on other people's PR:s over my GitHub mobile app, so I'll put this in an issue... 

> wouldn't it be possible to have the `ParallelScatterSplitter` and some corresponding `ParallelMainSplitter` in SMTS instead of OpenSMT?

Would this work against the original goal of not having to inherit from library (opensmt) code to implement the parallel solver? Do we need a better API?

_Originally posted by @blishko in https://github.com/usi-verification-and-security/opensmt/pull/471#pullrequestreview-945132151_

**Comment by blishko** [comment]
I did not know that was the original goal :)

Can you clarify what you mean by "inherit"?
I guess this is all a design choice.
My current view can be probably summarized as: If SMTS is required to run the parallel version of OpenSMT, then I would keep the parallel code there and we should try to find the best OpenSMT API to facilitate that.
If OpenSMT could be run in parallel on its own (+ `Channel`) I would see the point of having the parallel code inside OpenSMT.

I am willing to be convinced by a different opinion :)

**Comment by blishko** [comment]
OK, all sounds reasonable. No inheriting from OpenSMT classes in SMTS.

I would still like to spend some energy to see if a design with API is possible so that OpenSMT would not have to know about the `Channel` library.

**Comment by MasoudAsadzade** [comment]
PR #471:
All splitters-related codes have been moved to a separate directory as parallel with different binary named opensmt-splitter. The parallel library now is optional with minimal changes to the core of OpenSMT. when it is enabled, start to fetch PTPLib and add PTPLib as a library and finally link parallel and PTPLib against opensmt-splitter binary.
