### ISSUE TITLE
Add linter so pushed code will be automatically checked on the codestyle rules

### ISSUE THREAD

**Issue by BritikovKI** [usi-verification-and-security/opensmt#479]
It would be goodto automatically check/fix any troubles with the codestyle in the repository
Preferrably standard Google [linter](https://github.com/cpplint/cpplint#readme)

**Comment by aehyvari** [comment]
Checking sounds great!  I guess we don't want automatic fixes, or at least I can't see how that would fit in the workflow?

**Comment by BritikovKI** [comment]
> Checking sounds great! I guess we don't want automatic fixes, or at least I can't see how that would fit in the workflow?

Hmm it depends on the options set up in the linter, he may try to fix some lines automatically, but we can not just use this option

**Comment by blishko** [comment]
Sounds good. Now we just have to agree on the coding style :)

**Comment by blishko** [comment]
Yes, we can close this. We have already `clang-format` config in the repository. We just have to gradually go over all our files to fix the formatting.
