### ISSUE TITLE
Include information from git in the executable (if not building for releasing)

### ISSUE THREAD

**Issue by blishko** [usi-verification-and-security/opensmt#483]
To distinguish binaries built from different commits, we should include git commit hash in version message.
This hash should not be included when making an official release, so we need the mechanism to include that.

Also, it would be nice for developers to include warning if there were some uncommitted changes during the build process, so we know that executable does not correspond exactly to the git commit it claims to correspond to.

**Comment by Tomaqa** [comment]
Resolved by #801
