### ISSUE TITLE
Poor performance on printing nested terms in exposeClause of ScatterSplitter

### ISSUE THREAD

**Issue by MasoudAsadzade** [usi-verification-and-security/opensmt#521]
It seems on some of the benchmarks from QF_LIA, OpenSMT are so slow printing nested terms in exposeClause of ScatterSplitter.
For instance performance profile of ScatterSplitter on QF_LIA on: 

` 2400.00                   27.39                          nec-smt_large_bftpd_login_prp-9-50`

 shows very poor performance on printing nested terms in exposeClause of ScatterSplitter on this benchmark, and many others.

Comparing ScatterSplitter with a frequency of the clause sharing 15 second against SimpleOpenSMT solver. 
![non-incremental-QF_LIA-lemmaTimout-2022-06-17_vs_83f11053-2022-05-11](https://user-images.githubusercontent.com/17990258/174447281-c5d1afbd-6ee8-4e91-98b6-cd7bc0ef9d48.png)

Solution could be doing some sort of preprocessing to determine the length of the clause/partition or counting the deepness of the tree up-front to figure out if the clause should be shared or the literal used for partitioning.

**Comment by aehyvari** [comment]
Could you please re-run the experiment on #524 ?

**Comment by MasoudAsadzade** [comment]
> Could you please re-run the experiment on #524 ?
![non-incremental-QF_LIA-ptermNodeCounter-2022-06-20_vs_83f11053-2022-05-11](https://user-images.githubusercontent.com/17990258/174744336-449ac8c4-17a2-4b7a-aac7-e67c72ebf246.png)

**Comment by aehyvari** [comment]
We're getting there :)

On the instance `nec-smt_large_bftpd_login_prp-9-50` you quoted above, the problem seems somehow to be that the solver gets stuck on exposing unit clauses.  It takes over a minute to run the loop over the trail, and I didn't wait until it finished.  I now suggest a quick fix in #524 to limit the number of unit clauses to share to 100 and to pick them uniformly from the trail.

Would it be easy for you to rerun the experiment with the new commit?

**Comment by MasoudAsadzade** [comment]
I'm running the experiment...

**Comment by MasoudAsadzade** [comment]
Result of comparing opensmt binary against opensmt-splitter with clause_learning on a frequency of 15 second:
![non-incremental-QF_LIA-83f11053-2022-05-11_vs_ptermNodeCounter-2022-06-21](https://user-images.githubusercontent.com/17990258/174907625-f9b6f8a2-3cc9-4ca2-83f0-4661936f5f2b.png)

**Comment by MasoudAsadzade** [comment]
Looks very good!
