### ISSUE TITLE
Support for get-unsat-core

### ISSUE THREAD

**Issue by daniel-larraz** [usi-verification-and-security/opensmt#619]
It would be great to have support for `get-unsat-core`.

**Comment by Tomaqa** [comment]
Hello @daniel-larraz , can you test in your project whether the current solution works for you?

**Comment by daniel-larraz** [comment]
Hi @Tomaqa , I tested the latest version in the master branch and found a minor issue. Given this [input](https://github.com/usi-verification-and-security/opensmt/files/15487612/two_counters.lus.ic3qe.1.txt), OpenSMT returns an unsat core that includes a name that is not in context when the `get-unsat-core` command is executed. Specifically, OpenSMT returns `( c0 c14 c15 )`, but I was expecting `( c17 c14 c15 )` since the named term `c0` was asserted in a level of the assertion stack that was subsequently popped.

Thank you for your work!

**Comment by blishko** [comment]
Hi @daniel-larraz, thanks for the quick testing!
We have not tested unsat cores in incremental setting.
I have an idea where this issue could be coming from. We will investigate!

**Comment by blishko** [comment]
Hi @daniel-larraz, the issue should be fixed now.
Can you test on HEAD, or do you need an official release?

**Comment by daniel-larraz** [comment]
I can test on HEAD. I'll keep you posted.

**Comment by Tomaqa** [comment]
Thank you @daniel-larraz for the quick test.
We still keep the issue open, though, because the current implementation of the unsat cores is quite naive.

**Comment by blishko** [comment]
Actually, let's close this one.
We can document the effort on improving this functionality elsewhere.
