### ISSUE TITLE
SeqmentationFault or endless running query when using the API, due to logic combination or missing logic support.

### ISSUE THREAD

**Issue by kfriedberger** [usi-verification-and-security/opensmt#647]
Dear OpenSMT developers,

we are currently integrating OpenSMT into JavaSMT (https://github.com/sosy-lab/java-smt/pull/334) and we came to a unexpected behaviour of OpenSMT.
We use OpenSMT in version `2.5.2`, compiled from source.

I will start with a small example program:
The example is written in Java based on our own Java-API for OpenSMT, but it should also be working in C/C++.
```
    ArithLogic logic = LogicFactory.getLIAInstance();

    PTRef m_nc3 = logic.mkIntVar("m_nc3");
    PTRef aom_d = logic.mkIntVar("aom_d");
    PTRef m_i6 = logic.mkIntVar("m_i6");
    SRef arraySort = logic.getArraySort(logic.getSort_int(), logic.getSort_int());
    PTRef int1 = logic.mkVar(arraySort, "int1");

    PTRef zero = logic.mkIntConst("0");
    PTRef formula = logic.mkAnd(
        logic.mkGt(m_nc3, m_i6),
        logic.mkEq(
            zero,
            logic.mkIte(
                logic.mkLeq(zero, logic.mkSelect(int1, logic.mkPlus(aom_d, m_i6))),
                logic.mkIntConst("1"),
                zero
            )
        )
    );

    SMTConfig config = new SMTConfig();
    config.setOption(":produce-interpolants", new SMTOption(1));

    MainSolver mainSolver = new MainSolver(logic, config, "JavaSmt");
    mainSolver.push(formula);
    sstat check1 = mainSolver.check();
```

### Part 1:
The example applies the plain logic `LIA` for a query with an array sort, which is of course not valid.
However, the behaviour of OpenSMT is bad in that case: The example crashes with a segmentation fault in `mainSolver.check()` (more specifically: the stacktrace comes from `LASolver::getLAVar_single(PTRef)`). Would it be possible to throw a proper exception about some unsupported logic/feature in such a case? Even an exception about "missing LA var" would be better than a segmentation fault.

### Part 2:
If we disable the interpolant-production, or modify the formula a little bit (e.g., inline/simplify the ITE), the solver seems to run for more than 10 minutes without any result. Is this behaviour correct? We would also expect some exception about unsupported logic/feature.

Can some OpenSMT developer take a look and confirm this behaviour in OpenSMT? I am not that familiar with C++. Additionally, we would be happy about some fix for those cases.

**Comment by blishko** [comment]
Hello @kfriedberger!

I believe we are familiar with these issues. Proper fix would require nontrivial amount of work for which we currently do not have capacity.  
Add Part 1: Array support is not very mature yet, and interpolation does not work with arrays yet. As a quick fix, I think we should be able to throw an exception here. 

Add Part 2: I will investigate, but I will not be able to get to this this week, unfortunately.

**Comment by blishko** [comment]
Part 1 should now be fixed, OpenSMT will now throw an exception in this case.
Regarding part 2, when I tried the same example using our C++ API, with Logic correctly set to QF_ALIA, and interpolation disabled (it cannot be enabled for this Logic), the example finished immediately.

**Comment by kfriedberger** [comment]
**Details on part 2:**
We still use the previous version of OpenSMT (v2.5.2 from git commit 83fa637d).
The code from above is a little bit simplified, and suddenly runs much longer (I aborted after 10 minutes).
```
    ArithLogic logic = LogicFactory.getLIAInstance();

    PTRef m_nc3 = logic.mkIntVar("m_nc3");
    PTRef aom_d = logic.mkIntVar("aom_d");
    PTRef m_i6 = logic.mkIntVar("m_i6");
    SRef arraySort = logic.getArraySort(logic.getSort_int(), logic.getSort_int());
    PTRef int1 = logic.mkVar(arraySort, "int1");

    PTRef zero = logic.mkIntConst("0");
    PTRef formula = logic.mkAnd(
        logic.mkGt(m_nc3, m_i6),
        logic.mkNot(logic.mkLeq(zero, logic.mkSelect(int1, logic.mkPlus(aom_d, m_i6))))
    );

    SMTConfig config = new SMTConfig();
    // config.setOption(":produce-interpolants", new SMTOption(1));

    MainSolver mainSolver = new MainSolver(logic, config, "JavaSmt");
    mainSolver.push();
    mainSolver.insertFormula(formula);

    // endless running in next line
    sstat check1 = mainSolver.check();
```

As OpenSMT already has some improvements and updates, I will try to reproduce with the latest version soon.

**Comment by kfriedberger** [comment]
With the latest version 7f502169 the given example aborts when accessing array-sort. This behaviour is valid for the given logic. Thus, this issue does no longer exist and the ticket can be closed.

@blishko Thanks for your support and the changes in OpenSMT.
