### ISSUE TITLE
Explicitly divide `debug` and `release` builds

### ISSUE THREAD

**Issue by Tomaqa** [usi-verification-and-security/opensmt#664]
Currently, the debug/release mode must be specified in CMake and then `build` contains only this single mode. I consider this as inconvenient, for example in cases when I want to quickly switch from one mode to another.

I suggest resolving this the same way I dealt with it in my previous project: to explicitly divide builds `release` and `debug` in order to make them independent. Some IDEs use such architecture. Concrete solutions may differ, but in the first place, I would like to discuss the idea in general.

I am not experienced in CMake, just in GNU Make, so I am not sure if it is possible to easily arrive at something like this there. But I hope so.

**Comment by blishko** [comment]
You can create two separate build directories. Some IDEs, like CLion do this automatically.
I usually have `build` for release and then something like `build-debug` for debug build.

**Comment by Tomaqa** [comment]
I see. Can this be generalized? I.e. to support sth. like that independently of concrete IDE or whatever. Building in debug mode is also important in cases when a user wants to report a bug, so it should be straightforward for him/her.

I guess we can use the two separate directories `build` and `build-debug`, but it would be nice if the user was not required to explicitly do `mkdir build; cmake <opts> ..`. Instead, I think the directory/directories should be created automatically by `cmake` or by some script, and then the user chooses which one to `make`. I am not sure though how this would be consistent with IDEs.

I also do not like too much the inconsistency of the contents of `build`, although this is maybe already out of the scope of this issue. For example, there is nothing in `./build/bin`, and yet there is `./build/opensmt`. There is also `./bin` with some `opensmt.C` which is confusing.

**Comment by Tomaqa** [comment]
Main motivation: make it sufficient to use e.g. just `cmake` instead of `mkdir build; cd build; cmake ..`, and e.g. `cmake debug` instead of `mkdir build-debug; cd build-debug; cmake -DCMAKE_BUILD_TYPE=Debug ..`

**Comment by aehyvari** [comment]
We could add a script to do this if you want.

```
#!/bin/bash
mkdir build && cd build && cmake .. && make
```

cvc5 has a build script.  It might make providing some options a little more comfortable.

**Comment by blishko** [comment]
It looks like you can just run `cmake -B <build-dir>` in the root of our repository and it will prepare the build files in the specified `<build-dir>` (and create it for you). Then you can run `cmake --build <build-dir>` and it will start the build process.
So for `release` build the command should be ```cmake -B build && cmake --build build```
and for `debug` you can do ```cmake -B build-debug -DCMAKE_BUILD_TYPE=Debug && cmake --build build-debug```.

See https://cmake.org/cmake/help/latest/manual/cmake.1.html

We could add a very simple `Makefile` to our root that would just define the two build targets and run those commands.
