### ISSUE TITLE
Get rid of `readline` and GPL license

### ISSUE THREAD

**Issue by Tomaqa** [usi-verification-and-security/opensmt#675]
.. unless there is a serious reason why `readline` should be preferred over `libedit` (or how is is called).
I also think that `CMAKE_FLAGS=-DENABLE_LINE_EDITING:BOOL=ON` should be enabled by default, that is, to link with a line editing tool by default.
I do not see any drawback to doing so.

**Comment by blishko** [comment]
We explicitly make line editing opt-in, in order to not force unnecessary dependency on users who do not need it.

**Comment by Tomaqa** [comment]
I see, so it is not an integral part of the package and CMake has to check/download it, right?

**Comment by blishko** [comment]
I believe `CMake` will check if it can find it on your system and if not, it will report error (when you requested build with line editing capabilities).

**Comment by Tomaqa** [comment]
I think it would be neat if it was an optional dependency, but I guess that would require dynamic linkage instead of static. Then the library would be used only if it exists at runtime. But I guess none of us can do this with not too much effort ..
Until then, I guess that the current solution is sufficient.

**Comment by Tomaqa** [comment]
There is some reference to `readline` in `./regression`, but I do not understand the purpose of the tests (they fail on my machine) and not sure if its still being used

**Comment by aytey** [comment]
In `run-test.sh`, can you just change `-lreadline ` to be `-ledit`?

**Comment by blishko** [comment]
`./regression/run-test.sh` can be removed, it is not used anymore.
Regression tests use `run-test-notiming.sh` which don't mention `readline`.

**Comment by aytey** [comment]
> `./regression/run-test.sh` can be removed, it is not used anymore.

Seems like a better solution :D
