### ISSUE TITLE
Assertion failure at opensmt/src/logics/ArithLogic.cc:563

### ISSUE THREAD

**Issue by merlinsun** [usi-verification-and-security/opensmt#690]
Hi,
For this following instance, opensmt https://github.com/usi-verification-and-security/opensmt/commit/84f1c2b03d4864fe8e59b0aaf86baa8c843c4c5f 
```
$ opensmt small.smt2    
; this binary is compiled in debug mode (slow)
opensmt: /home/opensmt/src/logics/ArithLogic.cc:563: PTRef ArithLogic::mkMinus(vec<PTRef>&&): Assertion `args.size() == 2' failed.
Aborted (core dumped)
$ cat small.smt2 
(set-logic ALL)
(assert (= (- 0 0 0)))
```

**Comment by aehyvari** [comment]
Hi @merlinsun it's definitely not elegant behavior from opensmt, so to speak.  Thanks for pointing this out!

**Comment by blishko** [comment]
What is the expected behaviour of the minus operator with more than two arguments?
I was thinking that this could be just a parser error.
I have to check what SMT-LIB standard says about the minus operator.

**Comment by blishko** [comment]
Thank you!
We will try to fix the handling of the minus operator!
