### ISSUE TITLE
Assertion failure at src/logics/Logic.cc:653

### ISSUE THREAD

**Issue by merlinsun** [usi-verification-and-security/opensmt#694]
Hi, 
For this following instance, opensmt https://github.com/usi-verification-and-security/opensmt/commit/84f1c2b03d4864fe8e59b0aaf86baa8c843c4c5f

```
$ cat test.smt2 
(set-logic ALL)
(declare-fun x () Int)
(assert (= ""))
(check-sat)
$ opensmt test.smt2 
; this binary is compiled in debug mode (slow)
opensmt: /home/opensmt/src/logics/Logic.cc:653: virtual PTRef Logic::mkConst(const char*): Assertion `strlen(name) > 0' failed.
Aborted (core dumped)
```

I have prepared a fix that addresses this issue. I would appreciate it if you could review the PR at your convenience.

**Comment by blishko** [comment]
OpenSMT does not support strings, so this is not a valid input for our solver.
