### ISSUE TITLE
(Re)implement help message in the binary

### ISSUE THREAD

**Issue by Tomaqa** [usi-verification-and-security/opensmt#769]
Currently, option `-h` does nothing.

**Comment by blishko** [comment]
As far as I know, no one has tried to tweak the parameters for a long time. We are mostly happy with the current performance and we would have to evaluate every change on the whole of (supported) SMT-LIB benchmarks, which seems quite time and resource consuming.

**Comment by blishko** [comment]
It would also be good if `OpenSMT` could print its version.
