### ISSUE TITLE
Use annotated tags for releases

### ISSUE THREAD

**Issue by aehyvari** [usi-verification-and-security/opensmt#808]
At the moment in opensmt's git, the following happens
```
% git describe
OpenSMT-2.0.0-1533-g319deeed
```
That is, the version that git reports for opensmt is 2.0.0.  It look like [we should use annotated tags when doing releases](https://git-scm.com/docs/git-tag).

**Comment by blishko** [comment]
Or you can use `git describe --tags` instead :)

**Comment by Tomaqa** [comment]
Can this be integrated into the release GitHub action we recently added?

**Comment by blishko** [comment]
Not as it stands now, the Github action runs _after_ the release.
From what I have read, you need to create the annotated tag manually and then create a Github release from that tag.

**Comment by Tomaqa** [comment]
I force-pushed the tag `v2.8.0` to an annotated one.
However, now the following happens:
```
% git describe
v2.8.0-6-g90c49489
```
I am not sure what are the other use cases of annotated tags than for `git describe`.
But it seems a bit odd for me to name a tag `OpenSMT-...` inside of `opensmt` repository.
Hence, I guess that the current state is fine.

**Comment by aehyvari** [comment]
> Hence, I guess that the current state is fine?

Absolutely.  Probably `OpenSMT-` was part of the tag back then, which is not consistent with [semantic versioning](https://semver.org/).

**Comment by Tomaqa** [comment]
> Probably `OpenSMT-` was part of the tag back then, which is not consistent with [semantic versioning](https://semver.org/).

Shouldn't we even remove the letter `v` then? 😁

**Comment by aehyvari** [comment]
Probably we should, strictly speaking, but it's not the end of the world to me.

**Comment by Tomaqa** [comment]
I took a look at `z3` and `cvc5` and they both use tags in the form `<name>-<M>.<m>.<p>`, meaning they include the name of the solver (in lowercase). Hence, I would do the same and in this case use tag `opensmt-2.8.0` instead of `v2.8.0`.

**Comment by aehyvari** [comment]
I suggest not to do that.  I remember that we discussed this already once with @blishko long time ago and we explicitly decided not to include `opensmt` in the tag .  Reintroducing opensmt in the version would be kind of a regression with respect to that discussion.

**Comment by blishko** [comment]
> I suggest not to do that. I remember that we discussed this already once with @blishko long time ago and we explicitly decided not to include `opensmt` in the tag . Reintroducing opensmt in the version would be kind of a regression with respect to that discussion.

I don't quite remember what the reason behind that decision was.
