### ISSUE TITLE
Assertion violation at CoreSMTSolver.cc:2098 (incomplete fix?)

### ISSUE THREAD

**Issue by rainoftime** [usi-verification-and-security/opensmt#87]
Related and fixed issue https://github.com/usi-verification-and-security/opensmt/issues/63

The assertion is the same.

----

Hi, for this formula
[assert.txt](https://github.com/usi-verification-and-security/opensmt/files/4443457/assert.txt)

opensmt (commit 18c7c24d2) throws an assertion violation
~~~~
opensmt: /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/CoreSMTSolver.cc:2098: lbool CoreSMTSolver::search(int, int): Assertion `config.logic == opensmt::Logic_t::QF_UFIDL || config.logic == opensmt::Logic_t::QF_UFLRA' failed.
~~~~

**Comment by blishko** [comment]
Fixed by #91
